POST https://platzi-badges-api-kdhv.onrender.com/api/badges/create
Content-Type: application/json

{
  "_id": "2de30c429deb40fca41f05e6",
  "firstName": "Fredmeidemdeda",
  "lastName": "Grady",
  "email": "Leann_Berge@gmail.com",
  "jobTitle": "Legacy Brand Director",
  "twitter": "FredaGrady22221-7573",
  "avatarUrl": "https://www.gravatar.com/avatar/f63a9c45aca0e7e7de0782a6b1dff40b?d=identicon"
}